# Grunt aliases
---
# Build everything
build:
  - 'clean'
  - 'browserify'
  - 'newer:assemble'
  - 'useminPrepare'
  - 'sass'
  - 'postcss'
  - 'copy'
  - 'concat'
  - 'uglify'
  - 'usemin'
# Just the styling
styles:
  - 'sass'
  - 'postcss'
# Just the scripts
scripts:
  - 'clean'
  - 'browserify'
  - 'assemble'
  - 'useminPrepare'
  - 'copy'
  - 'concat'
  - 'uglify'
  - 'usemin'
# Server
server:
  - 'build'
  - 'connect'
  - 'watch'
# Default
default:
  - 'server'